version: '3'
services:
    crawler:
        build: .
        container_name: paste_bin_crawler
        links:
            - mongodb
        depends_on:
            - mongodb
        volumes:
          - ./:/home
        working_dir: /home
        command: python3 main.py

    mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        volumes:
          - ./docker-volume:/data/db
        ports:
            - 27017-27019:27017-27019
        command: mongod --logpath=/dev/null # --quiet
